[package]
name = "dev.peios.peios-installer"
architecture = "noarch"
description = "Complete Peios installer service, terminal, and automation surfaces"
license = "MIT"

[dependencies]
"dev.peios.installerd" = "= {{version}}-1"
"dev.peios.install-tui" = "= {{version}}-1"
"dev.peios.msip-drive" = "= {{version}}-1"


[files]
"@source:LICENSE" = "usr/share/licenses/dev.peios.peios-installer/LICENSE"
":usr/share/regim/installerd-service.reg" = "usr/share/regim/installerd-service.reg"
