[package]
name = "dev.peios.oobe"
architecture = "noarch"
description = "Complete Peios first-boot setup service and console surface"
license = "MIT"

[dependencies]
"dev.peios.oobed" = "= {{version}}-18"
"dev.peios.oobe-tui" = "= {{version}}-18"

[replaces]
"dev.peios.oobe" = "<= 0.1.0-7"

[files]
"@source:LICENSE" = "usr/share/licenses/dev.peios.oobe/LICENSE"
":usr/share/regim/oobe-service.reg" = "usr/share/regim/oobe-service.reg"
