[package]
name = "dev.peios.msip-drive-debuginfo"
description = "Debugging symbols for the MSIP automation client"

[dependencies]
"dev.peios.msip-drive" = "= {{version}}-1"
"dev.peios.peios-installer-debugsource" = "= {{version}}-1"

[files]
"@source:LICENSE" = "usr/share/licenses/dev.peios.msip-drive-debuginfo/LICENSE"
":licenses/**" = "usr/share/licenses/dev.peios.msip-drive-debuginfo/third-party"
":debug/msip-drive/usr/lib/debug/**" = "usr/lib/debug"
